### PR TITLE
feat: allow deleting contacts by identifier

### PR DESCRIPTION
**Pull request by KishanBagaria**
This PR makes it possible to delete contacts by identifier which is less error prone than by predicate when you want to delete a single contact.

#8

### CODE REVIEW

**Comment by codebytere** [comment]
This looks great too! Pulled it down and confirmed locally - mark this ready for review and i think we can get it merged :) Can you also add a PR body description for posterity?

**Comment by KishanBagaria** [comment]
Thanks for testing it out! I didn't because wasn't sure if it'd delete my contacts accidentally 😅

**Comment by codebytere** [comment]
@KishanBagaria normally for testing i make a bunch of fake contacts and try with those

**Review by codebytere — APPROVED** [review]

**Comment by KishanBagaria** [comment]
I did that too with the help of this library:


Didn't wanna risk it deleting all my contacts although unlikely. 😄

**Pull request merged**
