### PR TITLE
feat: allow updating contacts by identifier

### LINKED ISSUE #8: Return `identifier` with contacts
Can you return the [identifier](https://developer.apple.com/documentation/contacts/cncontact/1403103-identifier) with all contacts?

This'll allow changing the signature of the `updateContact` and `deleteContact` methods to identify a contact by an ID instead of a name, making it less error-prone and making it possible to delete contacts that don't have a name set.

I can attempt a PR for this if you like.

### PR DESCRIPTION
**Pull request by KishanBagaria**
#8

### CODE REVIEW

**Review by codebytere — CHANGES_REQUESTED** [review]
@KishanBagaria i'd prefer this not be a breaking change - we should see to enable users to pass in an identifier but not remove their ability to use a predicate

**Comment by KishanBagaria** [comment]
How do you propose the signature of the functions? deleteContactByIdentifier can be a different function. updateContact can be a different function too or accept identifier as a second argument.

**Comment by codebytere** [comment]
Thinking about this API structure a bit - i think i would be ok with some breaking changes, depending on how they were implemented. For `updateContact`, we shouldn't need to break anything since we can pass the `id` optionally as a part of the contact object to update, e.g:

```
// Change contact's nickname from Billy -> Will
const updated = contacts.updateContact({
  id: <some_id> 
  firstName: 'William',
  lastName: 'Grapeseed',
  nickname: 'Will'
})
```

For `deleteContact`, my current thinking is that it might be better in the long run to change the parameter to be an options object and contain something similar to that of `updateContact` - this will allow `id` to similarly be an optional parameter for a slightly more intuitive experience. There exist predicate [searches](https://developer.apple.com/documentation/contacts/cncontact/1403234-predicateforcontactsmatchingname?language=objc) for the other properties in there. That'd be a bit of code though - i'd also accept a change to an options object with fewer options, e.g `deleteContact({ name?: string, id?: string })` since that wouldn't require you change too much of what you already have.

Thanks for working on this, by the way!

**Comment by KishanBagaria** [comment]
Good idea, I've updated the PR. It's missing the core functionality still.

**Comment by codebytere** [comment]
This is looking good so far! what do you think about splitting it into a few PRs so we can get things merged faster? for example, adding `id` to the returned objects is already done. We can then work on update and delete without that blocking the first bits

**Comment by KishanBagaria** [comment]
Good idea! Splitting it up.

**Comment by KishanBagaria** [comment]
Should I split this in two again for delete and update functions?

**Comment by codebytere** [comment]
Up to you! that'd probably be faster though, yes :)

Do you also plan to allow fetching contacts by identifier? I was planning to add that as well but you're welcome to take it if you'd prefer

**Comment by KishanBagaria** [comment]
Don't quite have a use case for fetching contacts by identifier but someone might find it useful.

If the update listener specified the contact identifiers that were added/updated/deleted, it'd be very useful. I guess that's up to Apple to implement.

**Pull request closed without merging**
